language: python
python: 2.7
env:
- TOX_ENV=py26
- TOX_ENV=py27
- TOX_ENV=pep8

install:
- pip install tox
script:
- tox -vv -e $TOX_ENV

notifications:
  irc:
    channels:
      - "chat.freenode.net#teeth-dev"
    use_notice: true
    skip_join: true
  email: false
